feat(nvidia): Attempt to support NVIDIA open
ublue-os/akmods pull request #82
Opened 2023-10-22 04:20 UTC by EyeCantCU

2023-10-22 14:40 UTC, akdev1l requested changes

2023-10-22 14:40 UTC, akdev1l commented on .github/workflows/build.yml
> +        nvidia_varient: [none, proprietary, open]
Typo? varient > variant

2023-10-22 17:15 UTC, EyeCantCU commented on .github/workflows/build.yml
> +        nvidia_varient: [none, proprietary, open]
Corrected :)

2024-02-27 02:07 UTC, dylanmtaylor commented
Is this PR abandoned? If this is still desired, I could try to get this to completion.

2024-04-07 17:37 UTC, dylanmtaylor commented
I think this should be reworked on top of the negativo17 change that is currently in progress

2024-07-22 09:37 UTC, p5 commented
Superseded by #220

2024-07-22 09:37 UTC, closed without merging